name: Setup Bun
description: Setup bun and install dependencies

runs:
  using: composite
  steps:
    - name: 🥟 Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.4

    - name: 📦 Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
